### ISSUE TITLE
カレンダーの作成に関して

### ISSUE THREAD

**Issue by kodamarisa** [kodamarisa/osinotameni_yasetai#41]
- 質問内容・実現したいこと
カレンダーの作成に必要なviewsについて。
カレンダー作成時にviews/calendars/newがないためにエラーが発生しているのですが、基本使用するビューとして想定しているものはviews/calendars/showと考えていたので、困っています。
showビューをもとに新しくnewビューを作成した方がいいのでしょうか、それともコントロールの方を何か触った方がいいのでしょうか。
また、newビューを作成するとして、タイトル入力画面から移動した先がnewビューとなる場合にそこから別画面に移動した時に元のカレンダー画面に戻ってくるようにしたい場合はコントローラーは今の設定のままでいいのでしょうか。
- 現状発生している問題・エラーメッセージ
ローカルにて
```
[Webpacker] Compiling...
[Webpacker] Compiled all packs in /Users/kodamarisa/portfolio/osinotameni_yasetai/public/packs
[Webpacker] Hash: 9ba24c68b2e16122d3df
Version: webpack 4.47.0
Time: 447ms
Built at: 2024/07/22 15:38:36
                                         Asset      Size           Chunks                         Chunk Names
        js/application-a1bde62b69b4c3a4594a.js   231 KiB      application  [emitted] [immutable]  application
    js/application-a1bde62b69b4c3a4594a.js.map   250 KiB      application  [emitted] [dev]        application
    js/custom_calendar-b3ea2c5497a86691daac.js  4.41 KiB  custom_calendar  [emitted] [immutable]  custom_calendar
js/custom_calendar-b3ea2c5497a86691daac.js.map   4.2 KiB  custom_calendar  [emitted] [dev]        custom_calendar
           js/schedule-fa9ec990bc473820ec6e.js  4.86 KiB         schedule  [emitted] [immutable]  schedule
       js/schedule-fa9ec990bc473820ec6e.js.map  4.67 KiB         schedule  [emitted] [dev]        schedule
            js/sidebar-f6972234312c4d82fcbc.js   4.9 KiB          sidebar  [emitted] [immutable]  sidebar
        js/sidebar-f6972234312c4d82fcbc.js.map  4.78 KiB          sidebar  [emitted] [dev]        sidebar
                                 manifest.json  1.33 KiB                   [emitted]              
Entrypoint application = js/application-a1bde62b69b4c3a4594a.js js/application-a1bde62b69b4c3a4594a.js.map
Entrypoint custom_calendar = js/custom_calendar-b3ea2c5497a86691daac.js js/custom_calendar-b3ea2c5497a86691daac.js.map
Entrypoint schedule = js/schedule-fa9ec990bc473820ec6e.js js/schedule-fa9ec990bc473820ec6e.js.map
Entrypoint sidebar = js/sidebar-f6972234312c4d82fcbc.js js/sidebar-f6972234312c4d82fcbc.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/controllers sync recursive \.js$] ./app/javascript/controllers sync \.js$ 208 bytes {application} [built]
[./app/javascript/controllers/autocomplete_controller.js] 3.61 KiB {application} [optional] [built]
[./app/javascript/controllers/index.js] 257 bytes {application} [built]
[./app/javascript/packs/application.js] 584 bytes {application} [built]
[./app/javascript/packs/custom_calendar.js] 501 bytes {custom_calendar} {application} [built]
[./app/javascript/packs/schedule.js] 1010 bytes {schedule} {application} [built]
[./app/javascript/packs/sidebar.js] 1.02 KiB {sidebar} {application} [built]
    + 7 hidden modules

  Rendered layout layouts/application.html.erb (Duration: 1541.1ms | Allocations: 20440)
Completed 200 OK in 1566ms (Views: 1543.4ms | ActiveRecord: 6.9ms | Allocations: 35221)


Started POST "/calendars" for ::1 at 2024-07-22 15:38:40 +0900
Processing by CalendarsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "calendar"=>{"title"=>"あ"}, "commit"=>"Create Calendar"}
  Calendar Load (2.9ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 10], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:41:in `set_current_calendar'
Completed 500 Internal Server Error in 28ms (ActiveRecord: 2.9ms | Allocations: 5434)


  
ActionView::MissingTemplate (Missing template calendars/new, application/new with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/Users/kodamarisa/portfolio/osinotameni_yasetai/app/views"
  * "/Users/kodamarisa/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/devise-4.9.4/app/views"
  * "/Users/kodamarisa/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/simple_calendar-3.0.4/app/views"
  * "/Users/kodamarisa/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actiontext-6.1.7.7/app/views"
  * "/Users/kodamarisa/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionmailbox-6.1.7.7/app/views"
):
  
app/controllers/calendars_controller.rb:38:in `create'

```

- どの処理までうまく動いているのか
入力画面までは動いています。また、ゲスト機能をつける前まではカレンダーの作成は行えていました。

- 該当のソースコード
app/controllers/calendars_controller.rb
```
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_or_line_user!, except: [:index, :show, :new, :create, :edit, :update, :destroy] 

  def index
    @calendars = Calendar.all
  end

  def show
    if @calendar
      @customize = Customize.find_by(calendar_id: @calendar.id)
      @events = @calendar.schedules.includes(:exercise)
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
      return
    end
    expires_now
  end

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.new(calendar_params)
    if @calendar.save
      if current_guest
        @calendar.calendar_users.create(user: current_guest)
      end

      if params[:schedule].present?
        handle_successful_save
      else
        redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
      end
    else
      flash[:alert] = @calendar.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @calendar.update(calendar_params)
      redirect_to calendars_path, notice: 'Calendar was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find_by(id: params[:id])
    unless @calendar
      @calendar = Calendar.create(title: "Default Calendar")
      session[:current_calendar_id] = @calendar.id
    end
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image)
  end

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :exercise_id, :date, :repetitions, :duration)
  end

  def handle_successful_save
    @schedule = @calendar.schedules.build(schedule_params)
    if @schedule.save
      session[:current_calendar_id] = @calendar.id
      add_current_user_to_calendar if user_signed_in?
      redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
    else
      render :new
    end
  end

  def add_current_user_to_calendar
    @calendar.users << current_user
  end

  def add_current_line_user_to_calendar
    @calendar.line_users << current_line_user
  end
end
```

app/views/calendars/show.html.erb
```
<div class="calendar-header">
  <h1>Calendars#show</h1>
</div>

<div class="calendar-header">
  <% if @customize.present? && @customize.image.present? %>
    <%= image_tag @customize.image.url, class: 'calendar-image' %>
  <% else %>
    <p>No image available</p>
  <% end %>
</div>

<%= content_tag :div, class: "simple-calendar #{session[:calendar_color]}" do %>
  <%= month_calendar events: @events do |date, events| %>
    <div class="calendar-date">
      <%= link_to date.day, new_calendar_schedule_path(calendar_id: @calendar.id), class: 'date-link' %>
    </div>
    <div class="event-list">
      <% events.each do |event| %>
        <div class="event-item">
          <%= link_to event.exercise.name, calendar_schedule_path(@calendar, event), class: 'exercise-link' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
```
念の為、ゲスト機能関係も記載します。
app/controllers/application_controller.rb
```
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_line_user
  before_action :set_current_calendar

  helper_method :current_line_user, :line_user_signed_in?
  helper_method :current_guest
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_current_line_user
    if session[:line_user_id].present?
      @current_line_user = LineUser.find_by(id: session[:line_user_id])
    else
      @current_line_user = nil
    end
  end

  def current_line_user
    @current_line_user
  end

  def line_user_signed_in?
    @current_line_user.present?
  end

  def authenticate_user_or_line_user!
    unless current_user || current_line_user
      redirect_to root_path, alert: 'You must be logged in to access this section.'
    end
  end

  def set_current_calendar
    if params[:calendar_id].present?
      @current_calendar = Calendar.find_by(id: params[:calendar_id])
    elsif session[:current_calendar_id].present?
      @current_calendar = Calendar.find_by(id: session[:current_calendar_id])
    else
      @current_calendar = Calendar.create(title: "Default Calendar")
      session[:current_calendar_id] = @current_calendar.id
    end
  end

  def current_calendar
    @current_calendar
  end

  def current_guest
    if session[:guest_user_id]
      GuestUser.find(session[:guest_user_id])
    else
      guest = GuestUser.create!
      session[:guest_user_id] = guest.id
      guest
    end
  end
end
```

app/controllers/users/registrations_controller.rb
```
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def choose
    if user_signed_in?
      redirect_to user_profile_path
    end
  end

  # POST /resource
  def create
    super do |user|
      if session[:guest_user_id]
        guest_user = GuestUser.find(session[:guest_user_id])
        guest_calendars = Calendar.where(user_id: guest_user.id, user_type: 'GuestUser')

        guest_calendars.each do |calendar|
          calendar.update(user: user, user_type: 'User')
        end

        guest_user.destroy
        session.delete(:guest_user_id)
      end
    end
  end
```

app/models/calendar.rb
```
class Calendar < ApplicationRecord
  belongs_to :user, polymorphic: true

  has_many :calendar_users, dependent: :destroy
  has_many :users, through: :calendar_users, source: :user, source_type: 'User'
  has_many :line_users, through: :calendar_users, source: :user, source_type: 'LineUser'
  has_many :guest_users, through: :calendar_users, source: :user, source_type: 'GuestUser'
  has_many :schedules, dependent: :destroy

  validates :title, presence: true
end
```

app/models/guest_user.rb
```
class GuestUser < ApplicationRecord
  has_one :calendar, as: :user, dependent: :destroy

  after_create :create_guest_calendar

  private

  def create_guest_calendar
    self.create_calendar!(title: "Guest Calendar", user_type: "GuestUser", user_id: self.id)
  end
end
```
- エラーから考えられる原因
ゲスト機能を追加したことで発生したため、ゲスト機能にてカレンダーidが必要になったため、newビュー関連のエラーが出たのではと考えています。

- 試したこと
ChatGPTにも質問をしていますが、newビューが必要という結果になっています。

**Comment by kenchasonakai** [comment]
Railsはアクション名と対応するViewを探すのでnewアクションであれば通常new.html.erbを探します
違うファイルを探してほしい場合は`render :show`のように記載してあげると指定されたViewを探してくれるかなと思います

```
  def new
    @calendar = Calendar.new
    render :show
  end
```

ただ対応するviewそのまま使えたほうがRailsっぽいのでnew.html.erb作っちゃうのもよいかなと思います

**Comment by kodamarisa** [comment]
new.html.erbを作成しました！ありがとうございます！
