### ISSUE TITLE
本番環境下でのエラー

### ISSUE THREAD

**Issue by kodamarisa** [kodamarisa/osinotameni_yasetai#43]
- 質問内容・実現したいこと
トップページからカレンダー画面に移行をしたい。

- 現状発生している問題・エラーメッセージ
```
kodamarisa@kodamarisanoMacBook-Pro osinotameni_yasetai % heroku logs
2024-07-22T11:28:04.992875+00:00 app[web.1]: => Booting Puma
2024-07-22T11:28:04.992903+00:00 app[web.1]: => Rails 6.1.7.7 application starting in production
2024-07-22T11:28:04.992903+00:00 app[web.1]: => Run `bin/rails server --help` for more startup options
2024-07-22T11:28:06.014419+00:00 app[web.1]: Puma starting in single mode...
2024-07-22T11:28:06.014433+00:00 app[web.1]: * Puma version: 5.6.8 (ruby 3.1.4-p223) ("Birdie's Version")
2024-07-22T11:28:06.014435+00:00 app[web.1]: *  Min threads: 5
2024-07-22T11:28:06.014435+00:00 app[web.1]: *  Max threads: 5
2024-07-22T11:28:06.014435+00:00 app[web.1]: *  Environment: production
2024-07-22T11:28:06.014435+00:00 app[web.1]: *          PID: 2
2024-07-22T11:28:06.014628+00:00 app[web.1]: * Listening on http://0.0.0.0:54040
2024-07-22T11:28:06.018196+00:00 app[web.1]: Use Ctrl-C to stop
2024-07-22T11:28:06.514065+00:00 heroku[web.1]: State changed from starting to up
2024-07-23T11:32:40.696792+00:00 heroku[web.1]: Cycling
2024-07-23T11:32:40.699190+00:00 heroku[web.1]: State changed from up to starting
2024-07-23T11:32:41.211610+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2024-07-23T11:32:41.230636+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2024-07-23T11:32:41.233950+00:00 app[web.1]: Exiting
2024-07-23T11:32:41.307900+00:00 heroku[web.1]: Process exited with status 143
2024-07-23T11:32:46.607588+00:00 heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
2024-07-23T11:32:48.348234+00:00 app[web.1]: => Booting Puma
2024-07-23T11:32:48.348249+00:00 app[web.1]: => Rails 6.1.7.7 application starting in production
2024-07-23T11:32:48.348250+00:00 app[web.1]: => Run `bin/rails server --help` for more startup options
2024-07-23T11:32:49.228193+00:00 app[web.1]: Puma starting in single mode...
2024-07-23T11:32:49.228212+00:00 app[web.1]: * Puma version: 5.6.8 (ruby 3.1.4-p223) ("Birdie's Version")
2024-07-23T11:32:49.228212+00:00 app[web.1]: *  Min threads: 5
2024-07-23T11:32:49.228213+00:00 app[web.1]: *  Max threads: 5
2024-07-23T11:32:49.228213+00:00 app[web.1]: *  Environment: production
2024-07-23T11:32:49.228213+00:00 app[web.1]: *          PID: 2
2024-07-23T11:32:49.228483+00:00 app[web.1]: * Listening on http://0.0.0.0:38183
2024-07-23T11:32:49.231991+00:00 app[web.1]: Use Ctrl-C to stop
2024-07-23T11:32:49.418504+00:00 heroku[web.1]: State changed from starting to up
2024-07-24T12:04:42.651669+00:00 heroku[web.1]: Cycling
2024-07-24T12:04:42.654069+00:00 heroku[web.1]: State changed from up to starting
2024-07-24T12:04:43.211096+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2024-07-24T12:04:43.228612+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2024-07-24T12:04:43.230438+00:00 app[web.1]: Exiting
2024-07-24T12:04:43.308763+00:00 heroku[web.1]: Process exited with status 143
2024-07-24T12:04:48.094646+00:00 heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
2024-07-24T12:04:50.081780+00:00 app[web.1]: => Booting Puma
2024-07-24T12:04:50.081815+00:00 app[web.1]: => Rails 6.1.7.7 application starting in production
2024-07-24T12:04:50.081815+00:00 app[web.1]: => Run `bin/rails server --help` for more startup options
2024-07-24T12:04:50.994765+00:00 app[web.1]: Puma starting in single mode...
2024-07-24T12:04:50.994782+00:00 app[web.1]: * Puma version: 5.6.8 (ruby 3.1.4-p223) ("Birdie's Version")
2024-07-24T12:04:50.994785+00:00 app[web.1]: *  Min threads: 5
2024-07-24T12:04:50.994785+00:00 app[web.1]: *  Max threads: 5
2024-07-24T12:04:50.994786+00:00 app[web.1]: *  Environment: production
2024-07-24T12:04:50.994786+00:00 app[web.1]: *          PID: 2
2024-07-24T12:04:50.994955+00:00 app[web.1]: * Listening on http://0.0.0.0:4893
2024-07-24T12:04:50.998548+00:00 app[web.1]: Use Ctrl-C to stop
2024-07-24T12:04:51.568792+00:00 heroku[web.1]: State changed from starting to up
2024-07-25T09:27:20.000000+00:00 app[api]: Build started by user retedg623@gmail.com
2024-07-25T09:28:25.211496+00:00 app[api]: Release v41 created by user retedg623@gmail.com
2024-07-25T09:28:25.211496+00:00 app[api]: Deploy 599dc3a2 by user retedg623@gmail.com
2024-07-25T09:28:25.482328+00:00 heroku[web.1]: Restarting
2024-07-25T09:28:25.530064+00:00 heroku[web.1]: State changed from up to starting
2024-07-25T09:28:26.072332+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2024-07-25T09:28:26.090202+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2024-07-25T09:28:26.092499+00:00 app[web.1]: Exiting
2024-07-25T09:28:26.166035+00:00 heroku[web.1]: Process exited with status 143
2024-07-25T09:28:30.534148+00:00 heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
2024-07-25T09:28:32.590627+00:00 app[web.1]: => Booting Puma
2024-07-25T09:28:32.590647+00:00 app[web.1]: => Rails 6.1.7.7 application starting in production
2024-07-25T09:28:32.590647+00:00 app[web.1]: => Run `bin/rails server --help` for more startup options
2024-07-25T09:28:33.000000+00:00 app[api]: Build succeeded
2024-07-25T09:28:33.633291+00:00 app[web.1]: Puma starting in single mode...
2024-07-25T09:28:33.633314+00:00 app[web.1]: * Puma version: 5.6.8 (ruby 3.1.4-p223) ("Birdie's Version")
2024-07-25T09:28:33.633318+00:00 app[web.1]: *  Min threads: 5
2024-07-25T09:28:33.633318+00:00 app[web.1]: *  Max threads: 5
2024-07-25T09:28:33.633318+00:00 app[web.1]: *  Environment: production
2024-07-25T09:28:33.633318+00:00 app[web.1]: *          PID: 2
2024-07-25T09:28:33.633479+00:00 app[web.1]: * Listening on http://0.0.0.0:25496
2024-07-25T09:28:33.637713+00:00 app[web.1]: Use Ctrl-C to stop
2024-07-25T09:28:33.948166+00:00 heroku[web.1]: State changed from starting to up
2024-07-25T09:34:48.998388+00:00 app[api]: Starting process with command `rails db:migrate` by user retedg623@gmail.com
2024-07-25T09:34:57.335960+00:00 heroku[run.6366]: State changed from starting to up
2024-07-25T09:35:02.726495+00:00 heroku[run.6366]: Process exited with status 0
2024-07-25T09:35:02.757644+00:00 heroku[run.6366]: State changed from up to complete
2024-07-25T09:35:10.197692+00:00 app[web.1]: I, [2024-07-25T09:35:10.197617 #2]  INFO -- : [9e024902-4f79-4f7e-a477-f03684b79558] Started GET "/" for 49.98.116.32 at 2024-07-25 09:35:10 +0000
2024-07-25T09:35:10.199810+00:00 app[web.1]: I, [2024-07-25T09:35:10.199757 #2]  INFO -- : [9e024902-4f79-4f7e-a477-f03684b79558] Processing by HomeController#index as HTML
2024-07-25T09:35:10.272531+00:00 app[web.1]: I, [2024-07-25T09:35:10.272461 #2]  INFO -- : [9e024902-4f79-4f7e-a477-f03684b79558]   Rendered home/index.html.erb within layouts/application (Duration: 1.9ms | Allocations: 1690)
2024-07-25T09:35:10.273669+00:00 app[web.1]: I, [2024-07-25T09:35:10.273633 #2]  INFO -- : [9e024902-4f79-4f7e-a477-f03684b79558]   Rendered layout layouts/application.html.erb (Duration: 3.1ms | Allocations: 2857)
2024-07-25T09:35:10.273917+00:00 app[web.1]: I, [2024-07-25T09:35:10.273891 #2]  INFO -- : [9e024902-4f79-4f7e-a477-f03684b79558] Completed 200 OK in 74ms (Views: 4.5ms | ActiveRecord: 32.7ms | Allocations: 17521)
2024-07-25T09:35:10.275247+00:00 heroku[router]: at=info method=GET path="/" host=osinotameni-yasetai-8b5c48625703.herokuapp.com request_id=9e024902-4f79-4f7e-a477-f03684b79558 fwd="49.98.116.32" dyno=web.1 connect=0ms service=81ms status=200 bytes=2719 protocol=https
2024-07-25T09:35:10.530377+00:00 heroku[router]: at=info method=GET path="/assets/application-ea9a754f1344d248b487295ffa781e74eab915e98f8051fc57c55cb240ec50f5.css" host=osinotameni-yasetai-8b5c48625703.herokuapp.com request_id=f3c7ef7e-4973-4767-a005-4758061ec28c fwd="49.98.116.32" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2024-07-25T09:35:10.541745+00:00 heroku[router]: at=info method=GET path="/packs/js/application-c30df57bea7a6ea3b799.js" host=osinotameni-yasetai-8b5c48625703.herokuapp.com request_id=8a0c79dc-df09-4066-833b-64fd2a379a6d fwd="49.98.116.32" dyno=web.1 connect=0ms service=1ms status=200 bytes=28078 protocol=https
2024-07-25T09:35:11.048699+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=osinotameni-yasetai-8b5c48625703.herokuapp.com request_id=af41cd83-8244-48f0-944e-90e58f95bc65 fwd="49.98.116.32" dyno=web.1 connect=0ms service=1ms status=200 bytes=143 protocol=https
2024-07-25T09:35:13.724016+00:00 app[web.1]: I, [2024-07-25T09:35:13.723949 #2]  INFO -- : [7561fa6d-f28c-4e0e-91d7-85b32a368f11] Started POST "/calendars" for 49.98.116.32 at 2024-07-25 09:35:13 +0000
2024-07-25T09:35:13.725046+00:00 app[web.1]: I, [2024-07-25T09:35:13.725010 #2]  INFO -- : [7561fa6d-f28c-4e0e-91d7-85b32a368f11] Processing by CalendarsController#create as HTML
2024-07-25T09:35:13.725075+00:00 app[web.1]: I, [2024-07-25T09:35:13.725056 #2]  INFO -- : [7561fa6d-f28c-4e0e-91d7-85b32a368f11]   Parameters: {"authenticity_token"=>"[FILTERED]", "calendar"=>{"title"=>"あ"}, "commit"=>"Create Calendar"}
2024-07-25T09:35:13.741955+00:00 app[web.1]: I, [2024-07-25T09:35:13.741877 #2]  INFO -- : [7561fa6d-f28c-4e0e-91d7-85b32a368f11] Completed 500 Internal Server Error in 17ms (ActiveRecord: 10.8ms | Allocations: 4385)
2024-07-25T09:35:13.742667+00:00 app[web.1]: F, [2024-07-25T09:35:13.742633 #2] FATAL -- : [7561fa6d-f28c-4e0e-91d7-85b32a368f11]
2024-07-25T09:35:13.742669+00:00 app[web.1]: [7561fa6d-f28c-4e0e-91d7-85b32a368f11] ActiveModel::UnknownAttributeError (unknown attribute 'user_type' for Calendar.
2024-07-25T09:35:13.742669+00:00 app[web.1]: 
2024-07-25T09:35:13.742671+00:00 app[web.1]: raise UnknownAttributeError.new(self, k.to_s)
2024-07-25T09:35:13.742674+00:00 app[web.1]: ^^^^^):
2024-07-25T09:35:13.742676+00:00 app[web.1]: [7561fa6d-f28c-4e0e-91d7-85b32a368f11]
2024-07-25T09:35:13.742676+00:00 app[web.1]: [7561fa6d-f28c-4e0e-91d7-85b32a368f11] app/models/guest_user.rb:9:in `create_guest_calendar'
2024-07-25T09:35:13.742678+00:00 app[web.1]: [7561fa6d-f28c-4e0e-91d7-85b32a368f11] app/controllers/application_controller.rb:58:in `current_guest'
2024-07-25T09:35:13.742678+00:00 app[web.1]: [7561fa6d-f28c-4e0e-91d7-85b32a368f11] app/controllers/calendars_controller.rb:26:in `create'
2024-07-25T09:35:13.743480+00:00 heroku[router]: at=info method=POST path="/calendars" host=osinotameni-yasetai-8b5c48625703.herokuapp.com request_id=7561fa6d-f28c-4e0e-91d7-85b32a368f11 fwd="49.98.116.32" dyno=web.1 connect=0ms service=24ms status=500 bytes=1827 protocol=https
```
- どの処理までうまく動いているのか
ローカル環境ではトップページでのタイトル入力後カレンダー画面への移行はできている状態です。

- 該当のソースコード
app/models/calendar.rb
```
class Calendar < ApplicationRecord
  belongs_to :user, polymorphic: true

  has_many :calendar_users, dependent: :destroy
  has_many :users, through: :calendar_users, source: :user, source_type: 'User'
  has_many :line_users, through: :calendar_users, source: :user, source_type: 'LineUser'
  has_many :guest_users, through: :calendar_users, source: :user, source_type: 'GuestUser'
  has_many :schedules, dependent: :destroy

  validates :title, presence: true
end
```

app/models/calendae_user.rb
```
class CalendarUser < ApplicationRecord
  belongs_to :user, polymorphic: true
  belongs_to :calendar
end
```

app/controllers/application_controller.rb
```
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_line_user
  before_action :set_current_calendar

  helper_method :current_line_user, :line_user_signed_in?
  helper_method :current_guest
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_current_line_user
    if session[:line_user_id].present?
      @current_line_user = LineUser.find_by(id: session[:line_user_id])
    else
      @current_line_user = nil
    end
  end

  def current_line_user
    @current_line_user
  end

  def line_user_signed_in?
    @current_line_user.present?
  end

  def authenticate_user_or_line_user!
    unless current_user || current_line_user
      redirect_to root_path, alert: 'You must be logged in to access this section.'
    end
  end

  def set_current_calendar
    if params[:calendar_id].present?
      @current_calendar = Calendar.find_by(id: params[:calendar_id])
    elsif session[:current_calendar_id].present?
      @current_calendar = Calendar.find_by(id: session[:current_calendar_id])
    else
      @current_calendar = Calendar.create(title: "Default Calendar")
      session[:current_calendar_id] = @current_calendar.id
    end
  end

  def current_calendar
    @current_calendar
  end

  def current_guest
    if session[:guest_user_id]
      guest_user = GuestUser.find_by(id: session[:guest_user_id])
      return guest_user if guest_user
    end

    guest_user = GuestUser.create!
    session[:guest_user_id] = guest_user.id
    guest_user
  rescue ActiveRecord::RecordNotFound
    session.delete(:guest_user_id)
    guest_user = GuestUser.create!
    session[:guest_user_id] = guest_user.id
    guest_user
  end
end
```

app/controllers/calendars_controller.rb
```
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_or_line_user!, except: [:index, :show, :new, :create, :edit, :update, :destroy] 

  def index
    @calendars = Calendar.all
  end

  def show
    if @calendar
      @customize = Customize.find_by(calendar_id: @calendar.id)
      @events = @calendar.schedules.includes(:exercise)
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
      return
    end
    expires_now
  end

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.user = [current_user, current_guest, current_line_user].find(&:itself)

    if @calendar.user.nil?
      flash[:alert] = 'User must exist'
      render :new
      return
    end

    if @calendar.save
        @calendar.calendar_users.create(user: current_guest) if current_guest && @calendar.save

      if params[:schedule].present?
        handle_successful_save
      else
        redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
      end
    else
      error_messages = @calendar.errors.full_messages.join(', ')
      Rails.logger.error error_messages
      flash[:alert] = error_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @calendar.update(calendar_params)
      redirect_to calendars_path, notice: 'Calendar was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find_by(id: params[:id])
    unless @calendar
      @calendar = Calendar.create(title: "Default Calendar")
      session[:current_calendar_id] = @calendar.id
    end
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image)
  end

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :exercise_id, :date, :repetitions, :duration)
  end

  def handle_successful_save
    @schedule = @calendar.schedules.build(schedule_params)
    if @schedule.save
      session[:current_calendar_id] = @calendar.id
      add_current_user_to_calendar if user_signed_in?
      redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
    else
      render :new
    end
  end

  def add_current_user_to_calendar
    @calendar.users << current_user
  end

  def add_current_line_user_to_calendar
    @calendar.line_users << current_line_user
  end
end
```
- エラーから考えられる原因
ChatGPTではcalendarモデルにuser_typeという属性がないために起こっていると考えられる。という回答があるが、モデルにはuser_typeを作っているため、他にも原因があると考えているが見当がついていません。

- 試したこと
ローカルでは望んだ通りにtopページからカレンダー画面に移行できている状態なのは確認しています。

**Comment by kenchasonakai** [comment]
状況がわからないとなんとも言えないので、まずはもともとは動いていたものだと思うので動いていた時と動かなくなった時の差分やご自身で新しく実装したものでなにか関係がありそうなものがないか推測して教えてください

**Comment by kodamarisa** [comment]
遅くなってしまい、申し訳ございません。
自分で調べた結果、本番環境のマイグレーションが関係あるかもと思い、heroku run rails db:migrate:statusにて調べたところ以下の状態になっていました。
```
kodamarisa@kodamarisanoMacBook-Pro osinotameni_yasetai % heroku run rails db:migrate:status
Running rails db:migrate:status on ⬢ osinotameni-yasetai... up, run.2581 (Basic)

database: d7upeb6gbducdn

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20240513141645  ********** NO FILE **********
   up     20240515022111  Create users
   up     20240515022119  Create line users
   up     20240515022121  Create calendars
   up     20240515022341  Create exercises
   up     20240515022424  Create schedules
   up     20240515082212  Create bookmarks
   up     20240520100942  Create calendar users
   up     20240520191431  ********** NO FILE **********
   up     20240521124613  Create customizes
   up     20240522171655  ********** NO FILE **********
   up     20240523033740  ********** NO FILE **********
   up     20240523100252  ********** NO FILE **********
   up     20240524012957  ********** NO FILE **********
   up     20240605072804  Create guest users

```
もしかして、この「NO FILE」が何か関係しているのではと考えていますが、どうやって消去したらいいのかわかりません。念の為、ロールバックとリセットを行いましたが、「NO FILE」は残ったままになっています。

**Comment by kenchasonakai** [comment]
NoFileは関係ないような気はしますがデータベースのmigration周りに何か原因がありそうな場合は本番環境のユーザーデータとかは消えてしまいますがHerokuのデータベースを一度削除して作り直すとかすると綺麗に出来るかもです

https://qiita.com/mochi93kou/items/eb4b1e4952084048b13d

**Comment by kodamarisa** [comment]
返信遅くなってしまい申し訳ございません。
データベースを作り直した結果、トップページからカレンダー画面への移行が本番環境下でもできるようになりました。
「NO FILE」によりローカル環境下と本番環境下でのデータベースの状態が違ったために起こったエラーかなと感じました。
回答ありがとうございます。
