### ISSUE TITLE
POSTリクエストが送信できていない

### ISSUE THREAD

**Issue by kodamarisa** [kodamarisa/osinotameni_yasetai#44]
- 質問内容・実現したいこと
タイトル入力後にshow.html.erbの画面にリダレクトしたい。

- 現状発生している問題・エラーメッセージ
タイトル入力後にindex.html.erbにリダレクトしてしまう。
ログは以下のとおりとなっている
```
Started GET "/calendars/25" for ::1 at 2024-09-09 10:36:19 +0900
Processing by CalendarsController#show as HTML
  Parameters: {"id"=>"25"}
  Calendar Load (0.7ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 18], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:41:in `set_current_calendar'
  Calendar Load (1.5ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 25], ["LIMIT", 1]]
  ↳ app/controllers/calendars_controller.rb:73:in `set_calendar'
  GuestUser Load (0.6ms)  SELECT "guest_users".* FROM "guest_users" WHERE "guest_users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:54:in `current_guest'
  CACHE GuestUser Load (0.0ms)  SELECT "guest_users".* FROM "guest_users" WHERE "guest_users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:54:in `current_guest'
Redirected to http://localhost:3000/calendars
Completed 302 Found in 9ms (ActiveRecord: 2.8ms | Allocations: 3939)


Started GET "/calendars" for ::1 at 2024-09-09 10:36:19 +0900
Processing by CalendarsController#index as HTML
  Calendar Load (0.6ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 18], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:41:in `set_current_calendar'
  Rendering layout layouts/application.html.erb
  Rendering calendars/index.html.erb within layouts/application
  Rendered /Users/kodamarisa/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/simple_calendar-3.0.4/app/views/simple_calendar/_month_calendar.html.erb (Duration: 5.4ms | Allocations: 8360)
  Rendered calendars/index.html.erb within layouts/application (Duration: 8.0ms | Allocations: 9495)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered layouts/_header.html.erb (Duration: 0.5ms | Allocations: 118)
  Rendered layouts/_sidebar.html.erb (Duration: 0.8ms | Allocations: 480)
  Rendered layout layouts/application.html.erb (Duration: 16.1ms | Allocations: 16006)
Completed 200 OK in 21ms (Views: 17.7ms | ActiveRecord: 0.6ms | Allocations: 18200)

```
rails routesのログ
```
kodamarisa@kodamarisanoMacBook-Pro osinotameni_yasetai % rails routes
                                  Prefix Verb   URI Pattern                                                                                       Controller#Action
             static_pages_privacy_policy GET    /static_pages/privacy_policy(.:format)                                                            static_pages#privacy_policy
           static_pages_terms_of_service GET    /static_pages/terms_of_service(.:format)                                                          static_pages#terms_of_service
                                    root GET    /                                                                                                 home#index
                        new_user_session GET    /users/sign_in(.:format)                                                                          users/sessions#new
                            user_session POST   /users/sign_in(.:format)                                                                          users/sessions#create
                    destroy_user_session DELETE /users/sign_out(.:format)                                                                         users/sessions#destroy
                       new_user_password GET    /users/password/new(.:format)                                                                     users/passwords#new
                      edit_user_password GET    /users/password/edit(.:format)                                                                    users/passwords#edit
                           user_password PATCH  /users/password(.:format)                                                                         users/passwords#update
                                         PUT    /users/password(.:format)                                                                         users/passwords#update
                                         POST   /users/password(.:format)                                                                         users/passwords#create
                cancel_user_registration GET    /users/cancel(.:format)                                                                           users/registrations#cancel
                   new_user_registration GET    /users/sign_up(.:format)                                                                          users/registrations#new
                  edit_user_registration GET    /users/edit(.:format)                                                                             users/registrations#edit
                       user_registration PATCH  /users(.:format)                                                                                  users/registrations#update
                                         PUT    /users(.:format)                                                                                  users/registrations#update
                                         DELETE /users(.:format)                                                                                  users/registrations#destroy
                                         POST   /users(.:format)                                                                                  users/registrations#create
                   new_line_user_session GET    /login(.:format)                                                                                  users/sessions#new
                                   login POST   /login(.:format)                                                                                  users/sessions#create
               destroy_line_user_session GET    /logout(.:format)                                                                                 users/sessions#destroy
                         login_with_line GET    /line_login(.:format)                                                                             sessions#line_login
                                         GET    /auth/:provider/callback(.:format)                                                                sessions#create
                            auth_failure GET    /auth/failure(.:format)                                                                           redirect(301, /)
                     choose_registration GET    /choose_registration(.:format)                                                                    users/registrations#choose
                            user_profile GET    /profile(.:format)                                                                                users#profile
                      calendar_schedules GET    /calendars/:calendar_id/schedules(.:format)                                                       schedules#index
                                         POST   /calendars/:calendar_id/schedules(.:format)                                                       schedules#create
                   new_calendar_schedule GET    /calendars/:calendar_id/schedules/new(.:format)                                                   schedules#new
                  edit_calendar_schedule GET    /calendars/:calendar_id/schedules/:id/edit(.:format)                                              schedules#edit
                       calendar_schedule GET    /calendars/:calendar_id/schedules/:id(.:format)                                                   schedules#show
                                         PATCH  /calendars/:calendar_id/schedules/:id(.:format)                                                   schedules#update
                                         PUT    /calendars/:calendar_id/schedules/:id(.:format)                                                   schedules#update
                                         DELETE /calendars/:calendar_id/schedules/:id(.:format)                                                   schedules#destroy
                               calendars GET    /calendars(.:format)                                                                              calendars#index
                                         POST   /calendars(.:format)                                                                              calendars#create
                            new_calendar GET    /calendars/new(.:format)                                                                          calendars#new
                           edit_calendar GET    /calendars/:id/edit(.:format)                                                                     calendars#edit
                                calendar GET    /calendars/:id(.:format)                                                                          calendars#show
                  autocomplete_exercises GET    /exercises/autocomplete(.:format)                                                                 exercises#autocomplete
                      exercise_bookmarks POST   /exercises/:exercise_id/bookmarks(.:format)                                                       bookmarks#create
                                bookmark DELETE /bookmarks/:id(.:format)                                                                          bookmarks#destroy
                               exercises GET    /exercises(.:format)                                                                              exercises#index
                                exercise GET    /exercises/:id(.:format)                                                                          exercises#show
                        new_registration GET    /registrations/new(.:format)                                                                      registrations#new
                       line_registration GET    /line_registration(.:format)                                                                      line_users#line_registration
                      email_registration GET    /email_registration(.:format)                                                                     registrations#email_registration
                              line_users POST   /line_users(.:format)                                                                             line_users#create
                           new_line_user GET    /line_users/new(.:format)                                                                         line_users#new
                               line_user GET    /line_users/:id(.:format)                                                                         line_users#show
                              customizes POST   /customizes(.:format)                                                                             customizes#create
                           new_customize GET    /customizes/new(.:format)                                                                         customizes#new
                          edit_customize GET    /customizes/:id/edit(.:format)                                                                    customizes#edit
                               customize PATCH  /customizes/:id(.:format)                                                                         customizes#update
                                         PUT    /customizes/:id(.:format)                                                                         customizes#update
                               bookmarks GET    /bookmarks(.:format)                                                                              bookmarks#index
                          privacy_policy GET    /privacy_policy(.:format)                                                                         static_pages#privacy_policy
                        terms_of_service GET    /terms_of_service(.:format)                                                                       static_pages#terms_of_service
           rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
              rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
           rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
     rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
           rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
            rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
          rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
                                         POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
       new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
      edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                                 rails/conductor/action_mailbox/inbound_emails#edit
           rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
                                         PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
                                         PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
                                         DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#destroy
new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
   rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
   rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
                      rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
                rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
                                         GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
               rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
         rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
                                         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
                      rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
               update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
                    rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

```

- どの処理までうまく動いているのか
タイトル入力からの画面の推移の動作はできている。

- 該当のソースコード
app/controllers/calendars_controller.rb
```
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_or_line_user!, except: [:index, :show, :new, :create, :edit, :update, :destroy] 

  def index
    @calendars = Calendar.all
  end

  def show
    if @calendar
      if authorized_to_view?(@calendar)
        session[:current_calendar_id] = @calendar.id
        @customize = Customize.find_by(calendar_id: @calendar.id)
        @events = @calendar.schedules.includes(:exercise)
      else
        flash[:alert] = 'You are not authorized to view this calendar.'
        redirect_to calendars_path
      end
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
    expires_now
  end

  def new
    @calendar = Calendar.new
  end

  def create
    Rails.logger.debug "Create action called"
    @calendar = Calendar.new(calendar_params)
    @calendar.user = [current_user, current_guest, current_line_user].find(&:itself)

    if @calendar.user.nil?
      flash[:alert] = 'User must exist'
      render :new
      return
    end

    if @calendar.save
      Rails.logger.debug "Calendar saved successfully"
      @calendar.calendar_users.create(user: current_guest) if current_guest

      if params[:schedule].present?
        Rails.logger.debug "Schedule params present, calling handle_successful_save"
        handle_successful_save
      else
        Rails.logger.debug "Redirecting to calendar path"
        redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
      end
    else
      error_messages = @calendar.errors.full_messages.join(', ')
      Rails.logger.error error_messages
      flash[:alert] = error_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @calendar.update(calendar_params)
      redirect_to calendars_path, notice: 'Calendar was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find_by(id: params[:id])
    unless @calendar
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image, :color, :image_url)
  end

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :exercise_id, :date, :repetitions, :duration)
  end

  def handle_successful_save
    @schedule = @calendar.schedules.build(schedule_params)
    if @schedule.save
      session[:current_calendar_id] = @calendar.id
      add_current_user_to_calendar if user_signed_in?
      redirect_to calendar_path(@calendar), notice: 'Calendar was successfully created.'
    else
      render :new
    end
  end

  def add_current_user_to_calendar
    @calendar.users << current_user unless @calendar.users.include?(current_user)
  end

  def add_current_line_user_to_calendar
    @calendar.line_users << current_line_user unless @calendar.line_users.include?(current_line_user)
  end

  def authorized_to_view?(calendar)
    current_user && calendar.users.include?(current_user) ||
      current_line_user && calendar.line_users.include?(current_line_user) ||
      current_guest && calendar.users.include?(current_guest)
  end
end
```

app/views/calendars/new.html.erb
```
<%= form_with(model: @calendar, url: calendars_path, method: :post, local: true) do |form| %>
    <% if @calendar.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>
  
        <ul>
          <% @calendar.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="field">
      <%= form.label :color %>
      <%= form.text_field :color %>
    </div>

    <div class="field">
      <%= form.label :image_url %>
      <%= form.text_field :image_url %>
    </div>
  
    <div class="actions">
      <%= form.submit 'Create Calendar' %>
    </div>
  <% end %>
  
  <%= link_to 'Back', calendars_path %>
```

app/views/calendars/show.html.erb
```
<div class="calendar-header">
  <h1>Calendars#show</h1>
</div>

<div class="calendar-header">
  <% if @customize.present? && @customize.image.present? %>
    <%= image_tag @customize.image.url, class: 'calendar-image' %>
  <% else %>
    <p>No image available</p>
  <% end %>
</div>

<%= content_tag :div, class: "simple-calendar #{session[:calendar_color]}" do %>
  <%= month_calendar events: @events do |date, events| %>
    <div class="calendar-date">
      <%= link_to date.day, new_calendar_schedule_path(calendar_id: @calendar.id), class: 'date-link' %>
    </div>
    <div class="event-list">
      <% events.each do |event| %>
        <div class="event-item">
          <%= link_to event.exercise.name, calendar_schedule_path(@calendar, event), class: 'exercise-link' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
```

config/routes.rb
```
Rails.application.routes.draw do
  get 'static_pages/privacy_policy'
  get 'static_pages/terms_of_service'
  root 'home#index'

  # Devise routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }

  # Custom session routes
  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :new_line_user_session
    post '/login', to: 'users/sessions#create'
    get '/logout', to: 'users/sessions#destroy', as: :destroy_line_user_session
    get '/line_login', to: 'sessions#line_login', as: :login_with_line
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # User profile route
  authenticated :user do
    get '/choose_registration', to: 'users/registrations#choose', as: :choose_registration
    get '/profile', to: 'users#profile', as: :user_profile
  end
  
  # Calendar routes
  resources :calendars, except: [:destroy, :update] do
    resources :schedules, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  # Exercise routes
  resources :exercises, only: [:index, :show] do
    collection do
      get :autocomplete
    end
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
  
  # Registration routes
  resources :registrations, only: [:new]
  get '/line_registration', to: 'line_users#line_registration', as: :line_registration
  get '/email_registration', to: 'registrations#email_registration', as: :email_registration

  # LineUsers routes
  resources :line_users, only: [:show, :new, :create]

  # Customize routes
  resources :customizes, only: [:new, :edit, :create, :update]

  # Bookmarks route
  resources :bookmarks, only: [:index]

  # Static pages routes
  scope controller: :static_pages do
    get :privacy_policy
    get :terms_of_service
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
```

- エラーから考えられる原因
POSTリクエストがログにないため、フォームがうまく送信できていないと考えました。

- 試したこと
rails routesでのルート確認とChatGPTにて原因の絞り込みまではできましたが、原因の解消方法がわからない状態です。

**Comment by kenchasonakai** [comment]
Formから値が送信されてから実際にcreateアクション内で値が作られて画面が描画されるまでの流れは理解できていますか？

ここが理解できていたら原因がわかれば自分の認識と実際に行われる処理のどこに違いがあるのかをbinding.pryを使って変数などの中身を確認したり、ログなどを確認して一つ一つ確認していくとわかるのかなとも思います
また、上記を行ったうえで理解できないことがあるのであれば、どんなことを確認して、何を理解していて、どこが理解できないのかを明示して再度ご質問ください

**Comment by kenchasonakai** [comment]
> エラーから考えられる原因
POSTリクエストがログにないため、フォームがうまく送信できていないと考えました。

推測を行ったらで本当にそうなのか検証してみましょう
フォームの送信時に何も起きていないのか、代わりのなにかが起きているのかとうを一つ一つ分解しながらおかしなところがないか探ってみるとよいかと思います

**Comment by kodamarisa** [comment]
app/views/calendars/new.html.erbとapp/views/home/index.html.erbのコード内容が重複していたので、config/routes.rbのrootをcalendars#newに変更。
その後、デベロッパーにてリストを確認したところ、POSTリクエストは送信されていたため、送信自体はできていることがわかりました。これにより、なぜ受信できないのかとコードを見直した際に、app/controllers/calendars_controller.rbのauthorized_to_view?メソッドが正しく作動していないのではと思い、ChatGPTに質問したところ、ゲストユーザーはhas_one :calendar のためにcalendar.users.include?(current_guest)では関連付けが正しくチェックできないために望んだ通りの動作ができないのではと出たため、コードを以下のように変更した
```
def authorized_to_view?(calendar)
    if current_user
      calendar.users.include?(current_user)
    elsif current_line_user
      calendar.line_users.include?(current_line_user)
    elsif current_guest
      calendar.user == current_guest
    else
      false
    end
  end
```
以上の変更を行ったところ、タイトル入力後にshow.html.erbの画面にリダレクトが行えるようになりました。
